//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 06:32:55 AM MSK 
//


package by.it.sereda.jd02_09.taskc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Administrator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Flight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Dispatcher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Brigades">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Brigade" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Pilot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Navigator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Stewardess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "administrator",
    "flight",
    "dispatcher",
    "brigades"
})
@XmlRootElement(name = "Airport")
public class Airport {

    @XmlElement(name = "Administrator", required = true)
    protected String administrator;
    @XmlElement(name = "Flight", required = true)
    protected String flight;
    @XmlElement(name = "Dispatcher", required = true)
    protected String dispatcher;
    @XmlElement(name = "Brigades", required = true)
    protected Airport.Brigades brigades;

    /**
     * Gets the value of the administrator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdministrator() {
        return administrator;
    }

    /**
     * Sets the value of the administrator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdministrator(String value) {
        this.administrator = value;
    }

    /**
     * Gets the value of the flight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlight() {
        return flight;
    }

    /**
     * Sets the value of the flight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlight(String value) {
        this.flight = value;
    }

    /**
     * Gets the value of the dispatcher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatcher() {
        return dispatcher;
    }

    /**
     * Sets the value of the dispatcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispatcher(String value) {
        this.dispatcher = value;
    }

    /**
     * Gets the value of the brigades property.
     * 
     * @return
     *     possible object is
     *     {@link Airport.Brigades }
     *     
     */
    public Airport.Brigades getBrigades() {
        return brigades;
    }

    /**
     * Sets the value of the brigades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Airport.Brigades }
     *     
     */
    public void setBrigades(Airport.Brigades value) {
        this.brigades = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Brigade" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Pilot" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Navigator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Stewardess" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brigade"
    })
    public static class Brigades {

        @XmlElement(name = "Brigade")
        protected List<Airport.Brigades.Brigade> brigade;

        /**
         * Gets the value of the brigade property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the brigade property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBrigade().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Airport.Brigades.Brigade }
         * 
         * 
         */
        public List<Airport.Brigades.Brigade> getBrigade() {
            if (brigade == null) {
                brigade = new ArrayList<Airport.Brigades.Brigade>();
            }
            return this.brigade;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Pilot" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Navigator" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Stewardess" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pilot",
            "navigator",
            "stewardess"
        })
        public static class Brigade {

            @XmlElement(name = "Pilot", required = true)
            protected String pilot;
            @XmlElement(name = "Navigator", required = true)
            protected String navigator;
            @XmlElement(name = "Stewardess", required = true)
            protected String stewardess;

            /**
             * Gets the value of the pilot property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPilot() {
                return pilot;
            }

            /**
             * Sets the value of the pilot property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPilot(String value) {
                this.pilot = value;
            }

            /**
             * Gets the value of the navigator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNavigator() {
                return navigator;
            }

            /**
             * Sets the value of the navigator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNavigator(String value) {
                this.navigator = value;
            }

            /**
             * Gets the value of the stewardess property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStewardess() {
                return stewardess;
            }

            /**
             * Sets the value of the stewardess property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStewardess(String value) {
                this.stewardess = value;
            }

        }

    }

}
